### ISSUE TITLE
Can't install typescript above v3.3.3

### ISSUE THREAD

**Issue by Luchanso** [alfa-laboratory/arui-presets-ts#8]
For case when you try upgrade typescript above v3.3.3: 
```
Trace: 
  Invariant Violation: could not find a copy of typescript to link in /Users/luchanso/dev/my-project-name/node_modules/arui-presets-ts/node_modules
      at invariant (/usr/local/lib/node_modules/yarn/lib/cli.js:2168:15)
      at PackageLinker.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:47979:7)
      at Generator.next (<anonymous>)
      at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:315:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

This happen, because yarn@1.13.0 not correct resolve peerDependencies.
Removing typescript from peerDep fix this problem, but will spawn other problem with difference versions with arui-presets-ts and your project

More info about this bug: https://github.com/yarnpkg/yarn/issues/6285

**Comment by stepancar** [comment]
@Luchanso еще актуально?

**Comment by Luchanso** [comment]
Нет
